liip_imagine:
    # web_root: '%kernel.project_dir%/public'
    # web_path: '/uploads/documents'
    filter_sets:
        my_thumb_filter:
            quality: 80
            filters:
                thumbnail: { size: [100, 100], mode: outbound }