vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    image_vich:
      uri_prefix: /uploads/documents
      upload_destination: '%kernel.project_dir%/public/uploads/documents'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      # getter: getImageName